config/routes.rb
Rails.application.routes.draw do

root to: "welcomes#index"

devise_for :visitors

devise_for :guides, controllers: { registrations: "guides/registrations"}

get 'profile/:id', to: "profiles#profile", as: "profile"

resource :review_guides, except: [:new, :create]
get 'review_guide/guide/:id/new', to: "review_guides#new_review_guide"
post 'review_guide/guide/:id', to: "review_guides#create_review_guide"

resources :programs do
  get 'book_now/:event_id', to: "programs#book_now"
  post 'book_now/:event_id', to: "programs#book_now", as: "book"
  resources :reviews
end

end

app/models/event.rb
class Event < ActiveRecord::Base
	extend SimpleCalendar
	has_calendar attribute: :starts_at
	belongs_to :program
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :languages
  has_many :programs
  has_many :review_guides

end

app/models/language.rb
class Language < ActiveRecord::Base
	belongs_to :guide
end

app/models/program.rb
class Program < ActiveRecord::Base
	belongs_to :guide
	has_many :reviews
	has_many :events
	accepts_nested_attributes_for :events, reject_if: :all_blank, allow_destroy: true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :program
end

app/models/review_guide.rb
class ReviewGuide < ActiveRecord::Base
	belongs_to :guide
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
	# helper_method :month_calendar_td_options

	# def month_calendar_td_options
	# 	->(start_date, current_calendar_date) {
	# 	{class: "calendar-date", data: {day: current_calendar_date}}
	# 	}
	# end
end

app/controllers/guides/confirmations_controller.rb
class Guides::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/guides/passwords_controller.rb
class Guides::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/guides/sessions_controller.rb
class Guides::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/guides/unlocks_controller.rb
class Guides::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def profile
		@guide = Guide.find(params[:id])
	end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_guide!, except: [:show]
  respond_to :html

  def index
    @programs = Program.all
    respond_with(@programs)
  end

  def show
    @event_dates = @program.events
    respond_with(@program)
  end

  def book_now
    @program = Program.find(params[:program_id])
    @event_dates = @program.events
    @program.events.find(params[:event_id]).update(booked: true)
    #@program.update(city: "rennes")
    render action: :show
  end

  def new
    @program = Program.new
    @program.events.new
    respond_with(@program)
  end

  def edit
  end

  def create
    @program = Program.new(program_params)
    @program.guide_id = current_guide.id
    # @program.events.each do |event|
    #   event.update(booked: false)
    # end
    @program.save
    respond_with(@program)
  end

  def update
    @program.update(program_params)
    respond_with(@program)
  end

  def destroy
    @program.destroy
    respond_with(@program)
  end

  private
    def set_program
      @program = Program.find(params[:id])
    end

    def program_params
      params.require(:program).permit(:city, :length, :price, :description, :name, :transportation, events_attributes: [:starts_at, :ends_at, :booked])
    end
end

app/controllers/review_guides_controller.rb
class ReviewGuidesController < ApplicationController
  before_action :set_review_guide, only: [:show, :edit, :update, :destroy]
  before_action :set_guide
  before_action :authenticate_visitor!

  def new_review_guide
    @review_guide = ReviewGuide.new
  end

  def edit
  end

  def create_review_guide
    @review_guide = ReviewGuide.new(review_guide_params)
    @review_guide.guide_id = @guide.id
    if @review_guide.save
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def update
    @review_guide.update(review_guide_params)
  end

  def destroy
    @review_guide.destroy
  end

  private
    def set_review_guide
      @review_guide = ReviewGuide.find(params[:id])
    end

    def set_guide
      @guide = Guide.find(params[:id])
    end

    def review_guide_params
      params.require(:review_guide).permit(:rating, :comment)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_review, only: [:show, :edit, :update, :destroy]
	before_action :set_program
	before_action :authenticate_visitor!

	def new
		@review = Review.new
	end

	def edit
	end

	def create
		@review = Review.new(review_params)
		@review.program_id = @program.id

		if @review.save
			redirect_to @program
		else
			render 'new'
		end
	end
	
	def update
		@review.update(review_params)
	end

	def destroy
		@review.destroy
		redirect_to root_path
	end

	private

	def set_review
		@review = Review.find(params[:id])
	end

	def set_program
		@program = Program.find(params[:program_id])
	end

	def review_params
		params.require(:review).permit(:rating, :comment)
	end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	def index
		@programs = Program.all
		@guides = Guide.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/review_guides_helper.rb
module ReviewGuidesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/programs/_form.html.erb
<%= console%>
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :transportation %><br>
    <%= f.text_field :transportation %>
  </div>
  <div class="field">
    <%= f.fields_for :events do |event|%>
      <p>start</p>
      <%= event.date_select(:starts_at, order: [:day, :month, :year])%>
      <p>end</p>
      <%= event.date_select(:ends_at, order: [:day, :month, :year])%>
    <%end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<div class="pad-top">
<h1>Editing Program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>
	
</div>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Programs</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Length</th>
      <th>Price</th>
      <th>Description</th>
      <th>Name</th>
      <th>Transportation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.city %></td>
        <td><%= program.length %></td>
        <td><%= program.price %></td>
        <td><%= program.description %></td>
        <td><%= program.name %></td>
        <td><%= program.transportation %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<div class="pad-top">
<h1>New Program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>
	
</div>

app/views/programs/show.html.erb
<%# console%>
<p id="notice"><%= notice %></p>
<div class="container-fluid pad-top-show">
  <div class="row">
      <%= link_to "Write a Review", new_program_review_path(@program) %>
      <%= link_to 'Edit', edit_program_path(@program) %>
      <%= link_to 'Back', programs_path %>
  </div>
  <div class="row">
    <div class="col-xs-6">
      <div class="row">
        <p>
          <strong>Name:</strong>
          <%= @program.name %>
        </p>
      </div>   
      <div class="row">
        <p>
          <strong>City:</strong>
          <%= @program.city %>
        </p>
      </div>
      <div class="row">
        <p>
          <strong>Length:</strong>
          <%= @program.length %>
        </p>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="row">
        <p>
          <strong>Price:</strong>
          <%= @program.price %>
        </p>
      </div>
      <div class="row">
        <p>
          <strong>Description:</strong>
          <%= @program.description %>
        </p>
      </div>   
      <div class="row">
        <p>
          <strong>Transportation:</strong>
          <%= @program.transportation %>
        </p>
      </div> 
      <div class="row">
        <%#@event_dates.each do |date|%>
            <%# date.starts_at%>
            <%# date.ends_at%>          
        <%#end%>


        <%= month_calendar events: @event_dates do |date, events| %>
          <%= date %>
          <% events.each do |event| %>
            <div>
              <%if event.booked == nil%>
                <%= link_to "Book Now", program_book_path(@program.id, event.id), class: "btn btn-default"%>
              <%else%>
                Booked
              <%end%>
            </div>
          <% end %>
        <% end %>






      </div>     
    </div>
  </div> 
  <div class="book-now">
    <%# link_to "Book Now", program_book_path(@program.id), class: "btn btn-default"%>
  </div>
  <div class="row">
    <h3>Comments</h3>
    <ul>
      <% @program.reviews.each do |r|%>
        <li><%= r.comment%></li>
        <li><%= r.rating%></li> </br>
      <%end%>
    </ul>
  </div> 
</div>

app/views/review_guides/_form.html.erb
<%= form_for @review_guide, url: {action: "create_review_guide"}, html: {class: "nifty_form"} do |f|%>
  <% if @review_guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review_guide.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% @review_guide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/review_guides/edit.html.erb
<div class="pad-top">
<h1>Editing Review Guide</h1>

<%= render 'form' %>

<%= link_to 'Show', @review_guide %> |
<%= link_to 'Back', review_guides_path %>
	
</div>

app/views/review_guides/new_review_guide.html.erb
<div class="pad-top">
<h1>New Review Guide</h1>

<%= render 'form' %>

<%= link_to 'Back', review_guides_path %>

</div>