config/routes.rb
Rails.application.routes.draw do

root to: "welcomes#index"

devise_for :visitors

devise_for :guides, controllers: { registrations: "guides/registrations"}

get 'profile/:id', to: "profiles#profile", as: "profile"

resource :review_guides, except: [:new, :create]
get 'review_guide/guide/:id/new', to: "review_guides#new_review_guide"
post 'review_guide/guide/:id', to: "review_guides#create_review_guide"

resources :programs do
  get 'book_now/:event_id', to: "programs#book_now"
  post 'book_now/:event_id', to: "programs#book_now", as: "book"
  resources :reviews
end

end

app/models/event.rb
class Event < ActiveRecord::Base
	extend SimpleCalendar
	has_calendar attribute: :starts_at
	belongs_to :program
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :languages
  has_many :programs
  has_many :review_guides

end

app/models/language.rb
class Language < ActiveRecord::Base
	belongs_to :guide
end

app/models/program.rb
class Program < ActiveRecord::Base
	belongs_to :guide
	has_many :reviews
	has_many :events
	accepts_nested_attributes_for :events, reject_if: :all_blank, allow_destroy: true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :program
end

app/models/review_guide.rb
class ReviewGuide < ActiveRecord::Base
	belongs_to :guide
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
	# helper_method :month_calendar_td_options

	# def month_calendar_td_options
	# 	->(start_date, current_calendar_date) {
	# 	{class: "calendar-date", data: {day: current_calendar_date}}
	# 	}
	# end
end

app/controllers/guides/passwords_controller.rb
class Guides::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/guides/sessions_controller.rb
class Guides::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/guides/unlocks_controller.rb
class Guides::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def profile
		@guide = Guide.find(params[:id])
	end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_guide!, except: [:show]
  respond_to :html

  def index
    @programs = Program.all
    respond_with(@programs)
  end

  def show
    @event_dates = @program.events
    respond_with(@program)
  end

  def book_now
    @program = Program.find(params[:program_id])
    @event_dates = @program.events
    @program.events.find(params[:event_id]).update(booked: true)
    #@program.update(city: "rennes")
    render action: :show
  end

  def new
    @program = Program.new
    @program.events.new
    respond_with(@program)
  end

  def edit
  end

  def create
    @program = Program.new(program_params)
    @program.guide_id = current_guide.id
    # @program.events.each do |event|
    #   event.update(booked: false)
    # end
    @program.save
    respond_with(@program)
  end

  def update
    @program.update(program_params)
    respond_with(@program)
  end

  def destroy
    @program.destroy
    respond_with(@program)
  end

  private
    def set_program
      @program = Program.find(params[:id])
    end

    def program_params
      params.require(:program).permit(:city, :length, :price, :description, :name, :transportation, events_attributes: [:starts_at, :ends_at, :booked])
    end
end

app/controllers/review_guides_controller.rb
class ReviewGuidesController < ApplicationController
  before_action :set_review_guide, only: [:show, :edit, :update, :destroy]
  before_action :set_guide
  before_action :authenticate_visitor!

  def new_review_guide
    @review_guide = ReviewGuide.new
  end

  def edit
  end

  def create_review_guide
    @review_guide = ReviewGuide.new(review_guide_params)
    @review_guide.guide_id = @guide.id
    if @review_guide.save
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def update
    @review_guide.update(review_guide_params)
  end

  def destroy
    @review_guide.destroy
  end

  private
    def set_review_guide
      @review_guide = ReviewGuide.find(params[:id])
    end

    def set_guide
      @guide = Guide.find(params[:id])
    end

    def review_guide_params
      params.require(:review_guide).permit(:rating, :comment)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_review, only: [:show, :edit, :update, :destroy]
	before_action :set_program
	before_action :authenticate_visitor!

	def new
		@review = Review.new
	end

	def edit
	end

	def create
		@review = Review.new(review_params)
		@review.program_id = @program.id

		if @review.save
			redirect_to @program
		else
			render 'new'
		end
	end
	
	def update
		@review.update(review_params)
	end

	def destroy
		@review.destroy
		redirect_to root_path
	end

	private

	def set_review
		@review = Review.find(params[:id])
	end

	def set_program
		@program = Program.find(params[:program_id])
	end

	def review_params
		params.require(:review).permit(:rating, :comment)
	end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	def index
		@programs = Program.all
		@guides = Guide.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/review_guides_helper.rb
module ReviewGuidesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/profiles/profile.html.erb
<div class="pad-top">
<p><%= @guide.email%></p>

<%= link_to "review guide", "/review_guide/guide/#{@guide.id}/new"%>

<h3>Comments</h3>
  <ul>
    <% @guide.review_guides.each do |rg|%>
      <li><%= rg.comment%></li>
      <li><%= rg.rating%></li> </br>
    <%end%>
  </ul>	
</div>

app/views/reviews/_form.html.erb
<%= form_for([@program, @review]) do |f| %>
	<% if @review.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
			<ul>
				<% @review.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :comment %><br>
		<%= f.text_area :comment %>
	</div>

	<div class="field">
		<%= f.label :rating %><br>
		<%= f.number_field :rating %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>
	<%= render 'form' %>
<%= link_to 'Back', root_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>
	<%= render 'form' %>
<%= link_to 'Back', root_path %>

app/views/welcomes/index.html.erb
<!-- Intro Header white-->
<header class="intro">
	<div class="intro-body">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<h1 class="brand-heading">Be Local</h1>
					<p class="intro-text">Experience travelling locally<br>
					<% if visitor_signed_in? %>
						<%# link_to "New program", new_program_path%>
						<%= link_to "sign out",  destroy_visitor_session_path, method: :delete%>
					<%else%>
						<%=link_to "Start travelling local", new_visitor_registration_path%>/
						<%= link_to "Sign in traveller", new_visitor_session_path%>
					<%end%>
					</p>
					<a href="#about" class="btn btn-circle page-scroll">
						<i class="fa fa-angle-double-down animated"></i>
					</a>
				</div>
			</div>
		</div>
	</div>
</header>
<!-- Guide = about Section black-->
<section id="about" class="container content-section text-center">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2">
			<h2>Latest guides</h2>
			<p>If you beleive you are knowledgable enough to guide travellers for them to experience loccally you too become a guide !</p>
			<p><%= link_to "Become a guide !", new_guide_registration_path%>
			</p>
			<ul class="row">
			<%@guides.each do |g|%>
				<li class="col-xs-4">
					<%=link_to "profile/#{g.id}", class: "btn btn-default btn-lg" do %>
						<i class="fa fa-twitter fa-fw"></i><%= g.email%>
					<%end%>
				</li>
			<%end%>	
			</ul>
		</div>
	</div>
</section>
<!-- Programs Section white-->
<section id="program" class="content-section text-center">
	<div class="download-section">
		<div class="container">
			<div class="col-lg-8 col-lg-offset-2">
			<h2>Latest local programs</h2>
			<p>You can book a program of a local guide by signing-in as a traveller.</p>
			<ul class="row">
			<%@programs.each do |p|%>
				<li class="col-xs-4">
					<%=link_to p, class: "btn btn-default btn-lg" do%>
						<i class="fa fa-twitter fa-fw"></i><%= p.name%>
					<%end%>
				</li>
			<%end%>
			</ul>
			</div>
		</div>
	</div>
</section>