config/routes.rb
Rails.application.routes.draw do

root to: "welcomes#index"

devise_for :visitors

devise_for :guides, controllers: { registrations: "guides/registrations"}

get 'profile/:id', to: "profiles#profile", as: "profile"

resource :review_guides, except: [:new, :create]
get 'review_guide/guide/:id/new', to: "review_guides#new_review_guide"
post 'review_guide/guide/:id', to: "review_guides#create_review_guide"

resources :programs do
  get 'book_now/:event_id', to: "programs#book_now"
  post 'book_now/:event_id', to: "programs#book_now", as: "book"
  resources :reviews
end

end

app/models/event.rb
class Event < ActiveRecord::Base
	extend SimpleCalendar
	has_calendar attribute: :starts_at
	belongs_to :program
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :languages
  has_many :programs
  has_many :review_guides

end

app/models/language.rb
class Language < ActiveRecord::Base
	belongs_to :guide
end

app/models/program.rb
class Program < ActiveRecord::Base
	belongs_to :guide
	has_many :reviews
	has_many :events
	accepts_nested_attributes_for :events, reject_if: :all_blank, allow_destroy: true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :program
end

app/models/review_guide.rb
class ReviewGuide < ActiveRecord::Base
	belongs_to :guide
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
	# helper_method :month_calendar_td_options

	# def month_calendar_td_options
	# 	->(start_date, current_calendar_date) {
	# 	{class: "calendar-date", data: {day: current_calendar_date}}
	# 	}
	# end
end

app/controllers/guides/unlocks_controller.rb
class Guides::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def profile
		@guide = Guide.find(params[:id])
	end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_guide!, except: [:show]
  respond_to :html

  def index
    @programs = Program.all
    respond_with(@programs)
  end

  def show
    @event_dates = @program.events
    respond_with(@program)
  end

  def book_now
    @program = Program.find(params[:program_id])
    @event_dates = @program.events
    @program.events.find(params[:event_id]).update(booked: true)
    #@program.update(city: "rennes")
    render action: :show
  end

  def new
    @program = Program.new
    @program.events.new
    respond_with(@program)
  end

  def edit
  end

  def create
    @program = Program.new(program_params)
    @program.guide_id = current_guide.id
    # @program.events.each do |event|
    #   event.update(booked: false)
    # end
    @program.save
    respond_with(@program)
  end

  def update
    @program.update(program_params)
    respond_with(@program)
  end

  def destroy
    @program.destroy
    respond_with(@program)
  end

  private
    def set_program
      @program = Program.find(params[:id])
    end

    def program_params
      params.require(:program).permit(:city, :length, :price, :description, :name, :transportation, events_attributes: [:starts_at, :ends_at, :booked])
    end
end

app/controllers/review_guides_controller.rb
class ReviewGuidesController < ApplicationController
  before_action :set_review_guide, only: [:show, :edit, :update, :destroy]
  before_action :set_guide
  before_action :authenticate_visitor!

  def new_review_guide
    @review_guide = ReviewGuide.new
  end

  def edit
  end

  def create_review_guide
    @review_guide = ReviewGuide.new(review_guide_params)
    @review_guide.guide_id = @guide.id
    if @review_guide.save
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def update
    @review_guide.update(review_guide_params)
  end

  def destroy
    @review_guide.destroy
  end

  private
    def set_review_guide
      @review_guide = ReviewGuide.find(params[:id])
    end

    def set_guide
      @guide = Guide.find(params[:id])
    end

    def review_guide_params
      params.require(:review_guide).permit(:rating, :comment)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_review, only: [:show, :edit, :update, :destroy]
	before_action :set_program
	before_action :authenticate_visitor!

	def new
		@review = Review.new
	end

	def edit
	end

	def create
		@review = Review.new(review_params)
		@review.program_id = @program.id

		if @review.save
			redirect_to @program
		else
			render 'new'
		end
	end
	
	def update
		@review.update(review_params)
	end

	def destroy
		@review.destroy
		redirect_to root_path
	end

	private

	def set_review
		@review = Review.find(params[:id])
	end

	def set_program
		@program = Program.find(params[:program_id])
	end

	def review_params
		params.require(:review).permit(:rating, :comment)
	end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	def index
		@programs = Program.all
		@guides = Guide.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/review_guides_helper.rb
module ReviewGuidesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoolTour</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%# console %>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
				<i class="fa fa-bars"></i>
			</button>
			<%=link_to root_path, class: "navbar-brand page-scroll" do%>
				<i class="fa fa-play-circle"></i> <span class="light">Cool</span> Tour
			<%end%>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-right navbar-main-collapse">
			<ul class="nav navbar-nav">
			<!-- Hidden li included to remove active class from about link when scrolled up past about section -->
				<li class="hidden">
					<a href="#page-top"></a>
				</li>

				<li>
					<a class="page-scroll" data-target=".bs-example-modal-lg" data-toggle="modal" style="cursor: pointer;">How ?</a>
				</li>

			<% if guide_signed_in? %>
				<li>
					<%= link_to "New program", new_program_path%>
				</li>
				<li>
					<%= link_to "sign out",  destroy_guide_session_path, method: :delete%>
				</li>
			<%else%>
				<li>
					<%=link_to "Become a guide", new_guide_registration_path%>
				</li>
				<li>
					<%= link_to "Sign in guide", new_guide_session_path%>
				</li>
			<%end%>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>

<%= yield%>

<footer>
	<div class="wide_wrapper">
		<div id="logo">
			<div class="pad-left-footer"><i class="fa fa-copyright"></i></div>
			<div class="pad-left-footer">CoolTour</div>
			<div class="pad-left-footer"><%= Time.now.year %></div>
		</div>
		<nav class="navigation">
			<a href="#" data-toggle="tooltip" data-placement="top" title="FAQ" target="_blank"><i class="fa fa-question fa-2x"></i></a>
			<a onclick="myFace()" data-toggle="tooltip" data-placement="top" title="Be friendly !" target="_blank"><i class="fa fa-facebook-square fa-2x click"></i></a>
			<a href="https://monolok.github.io/online" data-toggle="tooltip" data-placement="top" title="Hire me !" target="_blank"><i class="fa fa-github fa-2x"></i></a>
			<a href="#" data-toggle="tooltip" data-placement="top" title="Donate BTC !" target="_blank"><i class="fa fa-btc fa-2x"></i></a>
			<a href="mailto:antoinebe35@gmail.com" data-toggle="tooltip" data-placement="top" title="Say hi !"><i class="fa fa-paper-plane fa-2x"></i></a>
		</nav>
	</div>
</footer>
<!-- Large modal -->
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      ...
    </div>
  </div>
</div>
</body>
</html>